### PR TITLE
CC-1134 Switching from terraform-library to terraform-module & recent Terraform improvements, .env file improvements, & Vault secrets improvements

### PR DESCRIPTION
**Pull request by harishkm2k**

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Review by hselvakumar — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Review by hselvakumar — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Review by tobafolaranmi-ch — APPROVED** [review]
lgtm

**Pull request merged**
